# Generated by Django 4.2.1 on 2023-05-10 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('destination', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('terminal', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[AB]$', 'Можна вводити лише символи A та B')])),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interpol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('dem_register', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('visa', models.IntegerField(blank=True, null=True)),
                ('luggage_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('wanted', models.IntegerField(choices=[(0, 'Not wanted'), (1, 'Wanted')])),
                ('flight_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
                ('passenger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('registration_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airport.registration')),
            ],
        ),
    ]
