# Generated by Django 4.2.1 on 2023-05-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_flight_interpol_registration_luggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpol',
            name='dem_register',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='dem_register',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
