# Generated by Django 4.2.1 on 2023-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_alter_interpol_dem_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='luggage_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='wanted',
            field=models.IntegerField(blank=True, choices=[(0, 'Not wanted'), (1, 'Wanted')], null=True),
        ),
    ]
